{{- if .Values.timescaledb.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: timescaledb-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.timescaledb.database.name | b64enc }}
  POSTGRES_USER: {{ .Values.timescaledb.database.user | b64enc }}
  POSTGRES_PASSWORD: {{ randAlphaNum 16 | b64enc }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timescaledb-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.timescaledb.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.timescaledb.persistence.size }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescaledb
  namespace: {{ .Values.global.namespace }}
  labels:
    app: timescaledb
    chart: {{ include "iot-stack-chart.chart" . }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timescaledb
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: timescaledb
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: timescaledb
        image: "{{ .Values.timescaledb.image.repository }}:{{ .Values.timescaledb.image.tag }}"
        imagePullPolicy: {{ .Values.timescaledb.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.timescaledb.service.port }}
        envFrom:
        - secretRef:
            name: timescaledb-secret
        volumeMounts:
        - name: timescaledb-storage
          mountPath: /var/lib/postgresql/data
        resources:
          {{- toYaml .Values.timescaledb.resources | nindent 10 }}
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - pg_isready -U {{ .Values.timescaledb.database.user }} -d {{ .Values.timescaledb.database.name }}
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: timescaledb-storage
        persistentVolumeClaim:
          claimName: timescaledb-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: timescaledb
  namespace: {{ .Values.global.namespace }}
  labels:
    app: timescaledb
    chart: {{ include "iot-stack-chart.chart" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.timescaledb.service.type }}
  ports:
  - port: {{ .Values.timescaledb.service.port }}
    targetPort: {{ .Values.timescaledb.service.port }}
    protocol: TCP
    name: postgres
  selector:
    app: timescaledb
    release: {{ .Release.Name }}
{{- end }}
