{{- if .Values.grafana.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  GF_SECURITY_ADMIN_USER: {{ .Values.grafana.admin.user | b64enc }}
  GF_SECURITY_ADMIN_PASSWORD: {{ randAlphaNum 16 | b64enc }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.grafana.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: {{ .Values.global.namespace }}
  labels:
    app: grafana
    chart: {{ include "iot-stack-chart.chart" . }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: grafana
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: grafana
        image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
        imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.grafana.service.port }}
        envFrom:
        - secretRef:
            name: grafana-secret
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        resources:
          {{- toYaml .Values.grafana.resources | nindent 10 }}
        readinessProbe:
          httpGet:
            path: /api/health
            port: {{ .Values.grafana.service.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Values.global.namespace }}
  labels:
    app: grafana
    chart: {{ include "iot-stack-chart.chart" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
  - port: {{ .Values.grafana.service.port }}
    targetPort: {{ .Values.grafana.service.port }}
    protocol: TCP
    name: http
  selector:
    app: grafana
    release: {{ .Release.Name }}
{{- end }}
