apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: datadog-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: datadog-secret
    creationPolicy: Owner
  data:
  - secretKey: api-key
    remoteRef:
      key: /iots6/datadog/api-key
